
sudo: false
language: python

cache:
  directories:
    - $HOME/env

before_install:
  - pip install hererocks
  - hererocks $HOME/env --luajit 2.0.4 --luarocks latest
  - source $HOME/env/bin/activate
  - git clone https://github.com/impulsh/gluacheck $HOME/gluacheck

install:
  - cd $HOME/gluacheck
  - luarocks make
  - cd $TRAVIS_BUILD_DIR

script:
  - luacheck .

before_deploy:


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master